browser:
    name: chrome
    webElement:
        timeOut: 60
        polling: 200
    attachScreenshot: true
    headless: true
activeEnvironment: prod
environments:
    test:
        app:
            url: http://146.59.32.4/
        user:
            email: adamnowak@poczta.pl
            password: haslo123
    prod:
        app:
            url: http://146.59.32.4/
        user:
            email: kamilpolak@poczta.pl
            password: trudnehaslo1

